apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tailscale

helmCharts:
  - name: tailscale-operator
    repo: https://pkgs.tailscale.com/helmcharts
    version: 1.80.3
    releaseName: tailscale-operator
    namespace: tailscale
    valuesFile: tailscale.values.yaml
