apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.9.0
    helm.sh/resource-policy: keep
  name: shortlinks.urlshortener.cedi.dev
spec:
  group: urlshortener.cedi.dev
  names:
    kind: ShortLink
    listKind: ShortLinkList
    plural: shortlinks
    singular: shortlink
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - jsonPath: .spec.target
          name: Target
          type: string
        - jsonPath: .spec.code
          name: Code
          type: string
        - jsonPath: .spec.after
          name: After
          type: string
        - jsonPath: .status.count
          name: Invoked
          type: string
      name: v1alpha1
      schema:
        openAPIV3Schema:
          description: ShortLink is the Schema for the shortlinks API
          properties:
            apiVersion:
              description:
                "APIVersion defines the versioned schema of this representation
                of an object. Servers should convert recognized schemas to the latest
                internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
              type: string
            kind:
              description:
                "Kind is a string value representing the REST resource this
                object represents. Servers may infer this from the endpoint the client
                submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
              type: string
            metadata:
              type: object
            spec:
              description: ShortLinkSpec defines the desired state of ShortLink
              properties:
                after:
                  default: 0
                  description:
                    RedirectAfter specifies after how many seconds to redirect
                    (Default=3)
                  format: int64
                  maximum: 99
                  minimum: 0
                  type: integer
                code:
                  default: 307
                  description:
                    Code is the URL Code used for the redirection. leave
                    on default (307) when using the HTML behavior. However, if you whish
                    to use a HTTP 3xx redirect, set to the appropriate 3xx status code
                  enum:
                    - 200
                    - 300
                    - 301
                    - 302
                    - 303
                    - 304
                    - 305
                    - 307
                    - 308
                  type: integer
                target:
                  description: Target specifies the target to which we will redirect
                  minLength: 1
                  type: string
              required:
                - target
              type: object
            status:
              description: ShortLinkStatus defines the observed state of ShortLink
              properties:
                count:
                  default: 0
                  description: Count represents how often this ShortLink has been called
                  minimum: 0
                  type: integer
              required:
                - count
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: {}
