---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  annotations:
    cluster.x-k8s.io/cluster-api-autoscaler-node-group-max-size: "1"
    cluster.x-k8s.io/cluster-api-autoscaler-node-group-min-size: "1"
  labels:
    nodepool: worker-x86
  name: worker-x86-nbg
  namespace: default
spec:
  clusterName: cedi-dev
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels: null
  template:
    metadata:
      labels:
        nodepool: worker-x86
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: worker-template-x86-taints
      clusterName: cedi-dev
      failureDomain: nbg1
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: HCloudMachineTemplate
        name: worker-x86-small
      version: v1.29.1
