global:
  extraEnv:
    - name: OTLP_ENDPOINT
      value: "tempo-distributor.observability.svc.cluster.local:4318"
    - name: OTLP_INSECURE
      value: "true"

urlshortener:
  replicaCount: 2
  autoscaling:
    enabled: false
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

  image:
    pullPolicy: Always
    tag: main

  podAnnotations:
    kubectl.kubernetes.io/default-container: urlshortener

  pdb:
    enabled: false
    minAvailable: 1

  ingress:
    enabled: true
    className: "nginx"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: ccl.pw
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: ccl-pw-tls
        hosts:
          - ccl.pw

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      interval: 10s
      
      additionalLabels:
        instance: primary

    rules:
      enabled: false

dashboard:
  replicaCount: 1
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

  image:
    pullPolicy: Always
    tag: main

  podAnnotations:
    kubectl.kubernetes.io/default-container: urlshortener-ui

  env:
    - name: REDIRECT_URL
      value: https://dash.ccl.pw/oauth/redirect
    - name: DASHBOARD_URL
      value: dash.ccl.pw
    - name: SHORTLINK_URL
      value: https://ccl.pw

  extraEnvFrom:
    - secretRef:
        name: urlshortener-oidc

  pdb:
    enabled: false
    minAvailable: 1

  ingress:
    enabled: true
    className: "nginx"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: dash.ccl.pw
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: dash-ccl-pw-tls
        hosts:
          - dash.ccl.pw

  metrics:
    enabled: false
    serviceMonitor:
      enabled: false
      interval: 10s

      additionalLabels:
        instance: primary

    rules:
      enabled: false