apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability

generators:
  - ./secret-generator.yaml

resources:
  - ../../../bases/grafana-promtail
  - ./egress.service.yaml
