apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "apiServer.fullname" . }}
  labels:
    {{- include "apiServer.labels" . | nindent 4 }}
spec:
  {{- if not .Values.apiServer.autoscaling.enabled }}
  replicas: {{ .Values.apiServer.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "apiServer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.apiServer.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "apiServer.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.apiServer.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "apiServer.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.apiServer.podSecurityContext | nindent 8 }}
      terminationGracePeriodSeconds: {{ .Values.apiServer.terminationGracePeriodSeconds }}
      containers:
        #- name: kube-rbac-proxy
        #  securityContext:
        #    allowPrivilegeEscalation: false
        #  image: gcr.io/kubebuilder/kube-rbac-proxy:v0.11.0
        #  imagePullPolicy: ifNotPresent
        #  args:
        #    - --secure-listen-address=0.0.0.0:8443
        #    - --upstream=http://127.0.0.1:8080/
        #    - --logtostderr=true
        #    - --v=0
        #  ports:
        #    - containerPort: 8443
        #      name: https
        #      protocol: TCP
        #  resources:
        #    limits:
        #      cpu: 500m
        #      memory: 128Mi
        #    requests:
        #      cpu: 5m
        #      memory: 64Mi
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.apiServer.securityContext | nindent 12 }}
          image: "{{ .Values.apiServer.image.repository }}:{{ .Values.apiServer.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.apiServer.image.pullPolicy }}
          command:
            - /urlshortener-api
          args:
            - --health-probe-bind-address=:8081
            - --bind-address=:8443
            - --metrics-bind-address=:{{ .Values.apiServer.metrics.service.servicePort }}
            
          {{- with .Values.apiServer.extraArgs }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.apiServer.service.port }}
              protocol: TCP
            {{- if .Values.apiServer.metrics.enabled }}
            - name: {{ .Values.apiServer.metrics.service.portName }}
              containerPort: {{ .Values.apiServer.metrics.service.servicePort }}
              protocol: TCP
            {{- end }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.apiServer.resources | nindent 12 }}
      {{- with .Values.apiServer.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.apiServer.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.apiServer.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
