apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: oauth2-proxy-chaos-mesh

resources:
  - ../../../../bases/oauth2-proxy

generators:
  - ./secret-generator.yaml

patchesJson6902:
  - target:
      kind: Deployment
      namespace: oauth2-proxy-chaos-mesh
      name: oauth2-proxy
    path: deployment.patch.yaml

  - target:
      kind: Ingress
      namespace: oauth2-proxy-chaos-mesh
      name: oauth2-proxy
    path: ingress.patch.yaml
