apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

resources:
  - ../../../bases/metrics-server

patches:
  - target:
      kind: Deployment
      version: v1
      name: metrics-server
      namespace: kube-system
    path: metrics-server.ds.patch.yaml
