# apiVersion: monitoring.grafana.com/v1alpha1
# kind: LogsInstance
# metadata:
#   name: logs
#   namespace: observability
#   labels:
#     agent: grafana-agent-logs
# spec:
#   clients:
#     - url: http://loki-gateway.observability.svc.cluster.local/loki/api/v1/push

#   # Supply an empty namespace selector to look in all namespaces. Remove
#   # this to only look in the same namespace as the LogsInstance CR
#   podLogsNamespaceSelector: {}
#   podLogsSelector: {}
#     # matchLabels:
#     #   instance: primary