apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: postgresql

helmCharts:
  - name: pgadmin4
    repo: https://helm.runix.net
    version: 1.23.1
    releaseName: pgadmin
    namespace: postgresql
    valuesFile: pgadmin-values.yaml

  - name: postgresql-ha
    repo: https://charts.bitnami.com/bitnami
    version: 12.8.2
    releaseName: pgadmin
    namespace: postgresql
    valuesFile: postgresha-values.yaml
